correction des formulaires et des routes offreform
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #124
Opened 2023-02-07 17:13 UTC by petaccia

2023-02-07 17:21 UTC, serpentaire approved these changes

2023-02-07 21:59 UTC, MartinezEmmanuel03 submitted a review, later dismissed

2023-02-08 10:20 UTC, KevinLavigne approved these changes

2023-02-08 10:23 UTC, serpentaire approved these changes

2023-02-08 14:12 UTC, KevinLavigne requested changes

2023-02-08 14:12 UTC, KevinLavigne commented on frontend/src/components/UI/OffreForm.jsx
> +    const newOffs = { ...offs };
copie de variable superflue

2023-02-08 14:34 UTC, petaccia commented
correction effectué

2023-02-08 14:41 UTC, arouxel17 approved these changes

2023-02-08 14:52 UTC, serpentaire approved these changes

2023-02-08 15:04 UTC, KevinLavigne approved these changes

2023-02-08 15:04 UTC, merged