add page profil with backend route post
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #18
Opened 2022-12-19 23:17 UTC by serpentaire

2022-12-20 08:24 UTC, kadev-oclock approved these changes

2022-12-20 08:25 UTC, MartinezEmmanuel03 approved these changes

2022-12-20 08:55 UTC, jujuck requested changes

2022-12-20 08:55 UTC, jujuck commented on backend/src/models/CandidatManager.js
> +  insert(Candidat) {
Candidat avec une minuscule partout => candidat 'respect du camelCase

2022-12-20 08:55 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +        setMessage("Profil succesfully added");
Pensez à mettre de suite un Toastify

2022-12-20 08:55 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +        setMessage("Profil not added");
idem toastify

2022-12-20 08:55 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +    e.preventDefault();
Il manque la vérification des champs obligatoires...

2022-12-20 08:55 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +  const sendForm = (e) => {
Si button en type button pas besoin de e.preventDefault

2022-12-20 10:12 UTC, arouxel17 approved these changes

2022-12-20 10:20 UTC, MartinezEmmanuel03 approved these changes

2022-12-20 10:21 UTC, arouxel17 approved these changes

2022-12-20 10:30 UTC, jujuck requested changes

2022-12-20 10:30 UTC, jujuck commented on backend/src/models/CandidatManager.js
> +
Not solved

2022-12-20 13:53 UTC, kadev-oclock approved these changes

2022-12-20 13:53 UTC, arouxel17 submitted a review, later dismissed

2022-12-20 13:53 UTC, MartinezEmmanuel03 approved these changes

2022-12-20 13:54 UTC, kadev-oclock commented on backend/src/models/CandidatManager.js
> +
ajout joi ok

2022-12-20 14:52 UTC, MartinezEmmanuel03 approved these changes

2022-12-20 15:36 UTC, jujuck submitted a review, later dismissed

2022-12-20 16:19 UTC, arouxel17 approved these changes

2022-12-20 16:19 UTC, MartinezEmmanuel03 approved these changes

2022-12-22 10:13 UTC, jujuck approved these changes

2022-12-22 10:13 UTC, merged