ajout de la base de donnée
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #3
Opened 2022-12-14 09:38 UTC by petaccia

2022-12-14 09:38 UTC, arouxel17 approved these changes

2022-12-14 09:40 UTC, kadev-oclock submitted a review, later dismissed
tout bon

2022-12-14 10:15 UTC, jujuck requested changes

2022-12-14 10:15 UTC, jujuck commented on backend/database.sql
> +USE `mydb` ;
renommer votre db avec le nom de votre projet

2022-12-14 10:15 UTC, jujuck commented on backend/database.sql
> +CREATE TABLE IF NOT EXISTS `mydb`.`` (
Creation d'une table vide ???

2022-12-15 15:36 UTC, jujuck approved these changes

2022-12-15 15:36 UTC, merged