Profil complement (add confirmation email, add photo avatar and cv, CSS, add select in photo and cv, updated JOI)
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #33
Opened 2022-12-29 11:02 UTC by serpentaire

2022-12-29 12:48 UTC, kadev-oclock submitted a review, later dismissed

2023-01-02 09:19 UTC, jujuck requested changes
Pas d'implémentation de mail de confirmation avec Email JS. On va passer par le back end pour le faire avec Email JS, mais bien vu

2023-01-02 09:19 UTC, jujuck commented on frontend/index.html
> +    <script
On passera pas un nodemailer 
dans notre back end pour faire le mail dans ce projet...

2023-01-02 09:19 UTC, jujuck commented on frontend/package.json
> +    "@emailjs/browser": "^3.10.0",
PAs de email js dans ce projet mais passage en node mailer en backend

2023-01-02 09:19 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +  const validateSignIn = () => {
Pas d'email js dans le projet. La validation de compte passera directement par le backend

2023-01-02 15:53 UTC, kadev-oclock submitted a review, later dismissed

2023-01-02 16:19 UTC, jujuck commented on frontend/package.json
> +    "@emailjs/browser": "^3.10.0",
Attention ton package est toujours installé, pense à npm uninstall @emailjs

2023-01-02 16:27 UTC, arouxel17 approved these changes

2023-01-02 16:27 UTC, kadev-oclock approved these changes

2023-01-03 08:00 UTC, jujuck approved these changes

2023-01-03 08:00 UTC, merged