Toastify offre form
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #39
Opened 2023-01-03 15:45 UTC by petaccia

2023-01-03 16:03 UTC, serpentaire submitted a review, later dismissed

2023-01-03 16:04 UTC, kadev-oclock approved these changes

2023-01-04 08:18 UTC, jujuck requested changes

2023-01-04 08:18 UTC, jujuck commented on frontend/src/pages/BackOffice/Offre.jsx
> +        toast.success(`Votre offre à bien été enregistrer`, toastiConfig);
Petites fautes d'orthographe (Conjugaison)

2023-01-04 09:37 UTC, serpentaire approved these changes

2023-01-04 13:08 UTC, kadev-oclock approved these changes

2023-01-04 13:53 UTC, arouxel17 approved these changes

2023-01-04 13:53 UTC, MartinezEmmanuel03 approved these changes

2023-01-04 15:07 UTC, jujuck approved these changes

2023-01-04 15:07 UTC, merged