Admin nav
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #45
Opened 2023-01-04 16:43 UTC by kadev-oclock

2023-01-04 17:02 UTC, serpentaire approved these changes

2023-01-04 17:40 UTC, petaccia approved these changes

2023-01-05 13:58 UTC, jujuck requested changes

2023-01-05 13:58 UTC, jujuck commented on frontend/src/components/UI/EntrepriseForm.jsx
> +              <span className="text-gray-700"> Addresse email</span>
Un seul d à adresse en français

2023-01-05 13:58 UTC, jujuck commented on frontend/.eslintrc.json
> +  "plugins": ["react", "import"],
Pourquoi y a t il le ce fichier dans la PR ainsi que les 2 fichiers package-lock ???? Ils n'on pas lieu d'être. Attention à tes git add

2023-01-05 14:48 UTC, kadev-oclock commented on frontend/src/components/UI/EntrepriseForm.jsx
> +              <span className="text-gray-700"> Addresse email</span>
ok c'est fait

2023-01-05 14:49 UTC, kadev-oclock commented on frontend/.eslintrc.json
> +  "plugins": ["react", "import"],
ok vu merci

2023-01-06 11:39 UTC, closed without merging