Complement upload profil le candidat peut mettre ou non une photo ou un cv
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #50
Opened 2023-01-05 21:02 UTC by serpentaire

Eslint n'a pas voulu que je mette une ternaire

2023-01-05 21:45 UTC, kadev-oclock submitted a review, later dismissed

2023-01-05 21:50 UTC, arouxel17 submitted a review, later dismissed

2023-01-06 08:06 UTC, jujuck requested changes

2023-01-06 08:06 UTC, jujuck commented on backend/src/controllers/candidatControllers.js
> +  if (req.files.avatar !== undefined) {
Peut être mettre un ternaire à la place pour profilPhoto ou profilCV

2023-01-06 08:07 UTC, serpentaire commented on backend/src/controllers/candidatControllers.js
> +  if (req.files.avatar !== undefined) {
comme j'ai mis dans le commentaire eslint n'en a pas voulu

2023-01-06 10:03 UTC, petaccia approved these changes

2023-01-06 10:37 UTC, jujuck approved these changes

2023-01-06 10:37 UTC, merged