creation de la table consultant et de ses données
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #56
Opened 2023-01-08 18:48 UTC by MartinezEmmanuel03

2023-01-08 19:24 UTC, petaccia submitted a review, later dismissed

2023-01-08 21:00 UTC, arouxel17 approved these changes

2023-01-09 09:25 UTC, jujuck requested changes

2023-01-09 09:25 UTC, jujuck commented on backend/database.sql
> +CREATE TABLE IF NOT EXISTS `externatic`.`consultant` (
Les consultants sont des profils, ils doivent être reliés à la table connexion via une clé étrangères

2023-01-16 15:05 UTC, arouxel17 submitted a review, later dismissed

2023-01-16 15:06 UTC, petaccia submitted a review, later dismissed

2023-01-18 09:18 UTC, jujuck requested changes

2023-01-18 09:18 UTC, jujuck commented on backend/database.sql
> +-- DROP TABLE IF EXISTS `externatic`.`candidature` ;
Est'il possible de mettre tous les drops dans l'ordre en haut de fichiers

2023-01-18 10:06 UTC, arouxel17 approved these changes

2023-01-18 10:08 UTC, petaccia approved these changes

2023-01-18 10:59 UTC, jujuck approved these changes

2023-01-18 10:59 UTC, merged