ajout route update/ajout form offre dashboard
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #58
Opened 2023-01-09 16:41 UTC by kadev-oclock

2023-01-09 16:55 UTC, MartinezEmmanuel03 approved these changes

2023-01-09 18:19 UTC, serpentaire approved these changes

2023-01-10 11:11 UTC, jujuck requested changes
Il manque les fonctions correctes pour ajouter l'élément avec retour de l'Id et mise à jour du state

2023-01-10 11:11 UTC, jujuck commented on backend/src/router.js
> +// router.delete('/entreprises/:id', deleteEntreprises);
Pas de code mort, merci de le supprimer

2023-01-10 11:11 UTC, jujuck commented on frontend/src/components/UI/EntrepriseForm.jsx
>    return (
Merci de reprendre toute l'indentation

2023-01-10 11:11 UTC, jujuck commented on frontend/src/components/UI/OffreForm.jsx
> +
Merci de retirer tous les espaces et lignes vides inutiles

2023-01-17 20:07 UTC, serpentaire approved these changes

2023-01-18 08:20 UTC, MartinezEmmanuel03 approved these changes

2023-01-18 11:12 UTC, jujuck requested changes

2023-01-18 11:12 UTC, jujuck commented on backend/src/models/EntrepriseManager.js
> +    return this.connection.query(
update ${this.table} set ? where id = ?, [entreprise, entreprise.id]... Si tu ajoute un champs, tu n'as pas besoin de modifier ta requête

2023-01-18 11:12 UTC, jujuck commented on frontend/src/App.jsx
> +            <Route path="/entreprises" element={<Entreprises />} />
Il y a 2 routes "entreprises" ???

2023-01-18 11:12 UTC, jujuck commented on frontend/src/App.jsx
>              <Route path="/offre" element={<Offre />} />
Quelle est la différence entre offres/:id et offre

2023-01-18 11:12 UTC, jujuck commented on frontend/src/components/UI/EntrepriseForm.jsx
> +  // fonction pour mettre à jour les dates en auto
A mettre en back end, faire le point avec Gaëtan

2023-01-18 11:12 UTC, jujuck commented on frontend/src/components/UI/OffreForm.jsx
> +      .then(() => {
Et l'on met le state à jour avec l'id récupérer ou ???

2023-01-18 11:12 UTC, jujuck commented on frontend/src/components/UI/OffreForm.jsx
> +              "
les " ne sont pas indentés correctement

2023-01-20 17:47 UTC, closed without merging