Form offre update
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #64
Opened 2023-01-18 11:39 UTC by petaccia

2023-01-18 13:15 UTC, MartinezEmmanuel03 requested changes
remettre le checkauth et son import dans le le fichier router.js

2023-01-18 13:34 UTC, MartinezEmmanuel03 submitted a review, later dismissed

2023-01-19 07:55 UTC, serpentaire approved these changes

2023-01-19 08:10 UTC, jujuck requested changes

2023-01-19 08:10 UTC, jujuck commented on backend/src/router.js
>  router.post("/offres", offreControllers.add);
Est'il possible d'ajouter la validation des données avec Joi en create et update

2023-01-19 08:10 UTC, jujuck commented on frontend/src/components/UI/OffreForm.jsx
> +    axios
Integration du apiConnexion en place d'axios

2023-01-19 08:10 UTC, jujuck commented on frontend/src/pages/BackOffice/Offre.jsx
> +    axios
Integration du apiConnexion en place d'axios

2023-01-19 08:20 UTC, jujuck requested changes

2023-01-19 08:20 UTC, jujuck commented on backend/src/models/OffreManager.js
> +    return this.connection.query(
Privilégie la requête `update ${this.table} set ? where id = ?`, [?, ?]

2023-01-24 08:28 UTC, closed without merging