Entreprise admin
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #68
Opened 2023-01-18 16:12 UTC by kadev-oclock

2023-01-18 16:17 UTC, MartinezEmmanuel03 requested changes
remettre les routes entrerprises post et put ne sont plus protégées

2023-01-18 16:21 UTC, serpentaire approved these changes

2023-01-19 08:14 UTC, jujuck requested changes

2023-01-19 08:14 UTC, jujuck commented on backend/src/router.js
> +router.post("/entreprises", entrepriseControllers.add);
Ajoute une validation de données sur les data entreprises en Create et Update

2023-01-19 08:14 UTC, jujuck commented on frontend/src/components/UI/EntrepriseForm.jsx
> +    axios
Remplace axios par apiConnexion

2023-01-23 18:57 UTC, kadev-oclock commented on backend/src/router.js
> +router.post("/entreprises", entrepriseControllers.add);
fait !

2023-01-23 18:59 UTC, serpentaire approved these changes

2023-01-24 08:29 UTC, petaccia approved these changes

2023-01-24 13:27 UTC, jujuck approved these changes

2023-01-24 13:28 UTC, merged