mise en place SIO sur les pages accessibles au candidats
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #78
Opened 2023-01-22 14:55 UTC by MartinezEmmanuel03

2023-01-22 15:14 UTC, arouxel17 approved these changes

2023-01-22 15:15 UTC, serpentaire approved these changes

2023-01-23 08:19 UTC, jujuck requested changes
Pensez à mettre à jour le index.html avec icon et titre d'accueil

2023-01-23 15:22 UTC, serpentaire approved these changes

2023-01-24 16:29 UTC, jujuck approved these changes

2023-01-24 16:29 UTC, merged