corrections liens dans le dashboard
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #79
Opened 2023-01-22 16:40 UTC by MartinezEmmanuel03

2023-01-22 16:47 UTC, serpentaire submitted a review, later dismissed

2023-01-22 18:54 UTC, arouxel17 approved these changes

2023-01-23 08:21 UTC, jujuck requested changes

2023-01-23 08:21 UTC, jujuck commented on frontend/src/components/UI/Sidebar.jsx
> +                  to="/dashboard/offre"
Mettre un "s" à offres car je pense qu'il y en a plusieurs dans la page

2023-01-23 08:21 UTC, jujuck commented on frontend/src/App.jsx
> +            <Route path="offre" element={<Offre />} />
Mettre un "s" à offres car je pense qu'il y en a plusieurs dans la page

2023-01-23 15:24 UTC, serpentaire approved these changes

2023-01-24 16:44 UTC, MartinezEmmanuel03 commented on frontend/src/App.jsx
> +            <Route path="offre" element={<Offre />} />
ce sera rajouté dans un fix

2023-01-25 08:30 UTC, arouxel17 approved these changes

2023-01-25 08:30 UTC, serpentaire approved these changes

2023-01-25 08:45 UTC, jujuck approved these changes

2023-01-25 08:45 UTC, merged