Admin offre
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #82
Opened 2023-01-24 07:58 UTC by petaccia

2023-01-24 07:59 UTC, serpentaire submitted a review, later dismissed

2023-01-24 08:35 UTC, kadev-oclock requested changes

2023-01-24 08:35 UTC, kadev-oclock commented on frontend/src/components/UI/OffreForm.jsx
> +      .get(`${import.meta.env.VITE_BACKEND_URL}/offres`)
Juste à enlever ${import.meta.env.VITE_BACKEND_URL} car tu as déjà apiConnexion

2023-01-24 08:35 UTC, kadev-oclock commented on frontend/src/pages/BackOffice/Offre.jsx
> +      .get(`${import.meta.env.VITE_BACKEND_URL}/offres`)
Remplacer axios par apiConnexion

2023-01-24 14:28 UTC, MartinezEmmanuel03 approved these changes

2023-01-24 16:09 UTC, kadev-oclock submitted a review, later dismissed

2023-01-24 16:11 UTC, serpentaire approved these changes

2023-01-25 08:02 UTC, serpentaire submitted a review, later dismissed

2023-01-25 08:04 UTC, arouxel17 submitted a review, later dismissed

2023-01-25 08:52 UTC, serpentaire approved these changes

2023-01-25 08:58 UTC, MartinezEmmanuel03 approved these changes

2023-01-25 13:43 UTC, closed without merging