browsing and securing session and profile
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #83
Opened 2023-01-24 14:35 UTC by serpentaire

2023-01-24 14:51 UTC, kadev-oclock submitted a review, later dismissed

2023-01-24 14:54 UTC, MartinezEmmanuel03 submitted a review, later dismissed

2023-01-24 16:37 UTC, jujuck requested changes

2023-01-24 16:37 UTC, jujuck commented on frontend/src/components/NavBar/NavBar.jsx
> +        <Link
Pas de LInk avec un onLcik fait un bouton et navigate

2023-01-25 08:03 UTC, petaccia approved these changes

2023-01-25 08:04 UTC, serpentaire commented
Modifier les link qui avaient un onclick par des a href

2023-01-25 08:04 UTC, arouxel17 submitted a review, later dismissed

2023-01-25 09:54 UTC, arouxel17 approved these changes

2023-01-25 10:03 UTC, MartinezEmmanuel03 approved these changes

2023-01-25 10:05 UTC, serpentaire commented
remplacer les "a herfa par des button avec une fonction et correction bug sur le updateProfil dans le fichier connexionManager

2023-01-25 10:11 UTC, jujuck approved these changes

2023-01-25 10:11 UTC, merged