Added confirmation email after registration
WildCodeSchool/2022-09-RMT-JSCREW-Externatic pull request #88
Opened 2023-01-25 21:28 UTC by serpentaire

2023-01-25 21:55 UTC, kadev-oclock approved these changes

2023-01-26 08:00 UTC, MartinezEmmanuel03 approved these changes

2023-01-26 13:16 UTC, jujuck requested changes

2023-01-26 13:16 UTC, jujuck commented on backend/src/router.js
> +const itemController = require("./controllers/itemControllers");
Renommer le controller en emailController

2023-01-26 13:16 UTC, jujuck commented on frontend/src/pages/Profil/Profil.jsx
> +    const email = {
Cette partie la sera faite en BAck end si ta requete de création est validée... et non en Front

2023-01-26 22:34 UTC, serpentaire commented on backend/src/router.js
> +const itemController = require("./controllers/itemControllers");
item changed by email

2023-01-26 22:35 UTC, serpentaire commented on frontend/src/pages/Profil/Profil.jsx
> +    const email = {
l'email est envoyé depuis le back et j'ai stylisé le corps de l'email

2023-01-27 08:20 UTC, kadev-oclock approved these changes

2023-01-27 08:29 UTC, kadev-oclock approved these changes

2023-01-27 08:30 UTC, arouxel17 approved these changes

2023-01-27 08:33 UTC, jujuck approved these changes

2023-01-27 08:33 UTC, merged